data:
  patch_size: 1024
  perturbation: 384
  negative_sample_prob: 0.12
  non_sky_bias: 0.5
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints