name: pidnet-cp-32-best-params
cv_name: pidnet-cp-32-best-params

epochs: 50
optimized_metrics:
  - cables/quality
  - poles/quality
verbose: false
minimal_logging: false

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.055017282997368556
    flip:
      enabled: true
    multi_scale:
      enabled: true
      scale_factor: 5

  downsampling_factor: 32
  patch_size: 1024
  perturbation: 890
  negative_sample_prob: 0.0204275375063882
  non_sky_bias: 0.5
  num_workers:
    train: 20
    val: 6
  batch_size:
    train: 23
    val: 2
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  poles_weight: 1.1764195452078914
  ohem:
    enabled: true
    threshold: 0.9800429855795345
    keep_fraction: 0.732849147887819

optimizer:
  name: adam
  lr: 0.0004910251523365226
  wd: 0.0000028942826912761242
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

checkpointing:
  enabled: false

visualization:
  n_images_per_epoch: 0
  every: 100
