name: pidnet-cables-and-poles
cv_name: null

epochs: 30
optimized_metrics:
  - cables/quality
  - poles/quality
verbose: false
minimal_logging: true

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.14639701572025943
    flip:
      enabled: true
    multi_scale:
      enabled: false
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 253  #  = 0.24736219457734454 * 1024
  negative_sample_prob: 0.2310396916551909
  non_sky_bias: 0.5
  num_workers:
    train: 12
    val: 6
  batch_size:
    train: 39
    val: 6
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  poles_weight: 1.772283707381064
  ohem:
    enabled: true
    threshold: 0.9
    keep_fraction: 0.125

optimizer:
  name: adam
  lr: 0.00043717438222708904
  wd: 0.0029946772925411426
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

visualization:
  n_images_per_epoch: 0
  every: 100
