name: pidnet-cables-and-poles-default-hp
cv_name: null

epochs: 40
optimized_metrics:
  - cables/quality
  - poles/quality
verbose: false
minimal_logging: false

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.03131800152990488
    flip:
      enabled: true
    multi_scale:
      enabled: false
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 388
  negative_sample_prob: 0.13773327245748596
  non_sky_bias: 0.5
  num_workers:
    train: 14
    val: 6
  batch_size:
    train: 3
    val: 1
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  poles_weight: 1.222336583670382
  ohem:
    enabled: true
    threshold: 0.9
    keep_fraction: 0.125

optimizer:
  name: adam
  lr: 0.000053174707862687346
  wd: 0.000042226933671866335
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

visualization:
  n_images_per_epoch: 0
  every: 100
