name: pidnet-cables-and-poles-v2
cv_name: null

epochs: 60
optimized_metrics:
  - cables/quality
  - poles/quality
verbose: false
minimal_logging: false

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.07276887652965638
    flip:
      enabled: true
    multi_scale:
      enabled: false
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 788
  negative_sample_prob: 0.1201110883482061
  non_sky_bias: 0.5
  num_workers:
    train: 15
    val: 6
  batch_size:
    train: 8
    val: 2
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  poles_weight: 3.5784599991763812
  ohem:
    enabled: true
    threshold: 0.5
    keep_fraction: 0.375

optimizer:
  name: adam
  lr: 0.00026546297924107056
  wd: 0.00003328371707969199
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

checkpointing:
  enabled: true

visualization:
  n_images_per_epoch: 0
  every: 100
