name: pidnet-cables
cv_name: null

epochs: 30
optimized_metric: quality
verbose: false

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.03131800152990488
    flip:
      enabled: true
    multi_scale:
      enabled: false
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 388  #  = 0.37911889126640125 * 1024
  negative_sample_prob: 0.13049906840749562
  non_sky_bias: 0.5
  num_workers:
    train: 12
    val: 6
  batch_size:
    train: 3
    val: 6
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  ohem:
    enabled: true
    threshold: 0.9
    keep_fraction: 0.125

optimizer:
  name: adam
  lr: 0.000053174707862687346
  wd: 0.000042226933671866335
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

visualization:
  n_images_per_epoch: 3
  every: 1
