name: pidnet-cables-and-poles-v1
cv_name: null

epochs: 30
optimized_metrics:
  - cables/quality
  - poles/quality
verbose: false
minimal_logging: false

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.038364487119429296
    flip:
      enabled: true
    multi_scale:
      enabled: false
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 587
  negative_sample_prob: 0.02850794761689004
  non_sky_bias: 0.5
  num_workers:
    train: 15
    val: 6
  batch_size:
    train: 8
    val: 2
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  poles_weight: 1.377118238359857
  ohem:
    enabled: true
    threshold: 0.9
    keep_fraction: 0.125

optimizer:
  name: adam
  lr: 0.00026546297924107056
  wd: 0.00003328371707969199
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

checkpointing:
  enabled: true

visualization:
  n_images_per_epoch: 0
  every: 100
