name: pidnet-cables

epochs: 30
optimized_metric: quality

data:
  augmentations:
    color_jitter:
      enabled: true
      magnitude: 0.2
    flip:
      enabled: true
    multi_scale:
      enabled: true
      scale_factor: 15

  downsampling_factor: 16
  patch_size: 1024
  perturbation: 384
  negative_sample_prob: 0.12
  non_sky_bias: 0.5
  num_workers:
    train: 12
    val: 4
  batch_size:
    train: 12
    val: 4
  cv:
    num_folds: 5
    fold: null
    folds_select: null
    parallel: []
  size:
    train: null
    val: null

loss:
  ohem:
    enabled: true
    threshold: 0.9
    keep_fraction: 0.125

optimizer:
  name: adam
  lr: 1e-4
  wd: 1e-4
  adjust_lr: false

paths:
  complete_frames: /scratch/cvlab/home/gwizdala/dataset/processed/daedalean/complete_frames
  annotations: /scratch/cvlab/home/gwizdala/dataset/daedalean/cable-annotations
  checkpoints: /scratch/cvlab/home/gwizdala/output/checkpoints

validation:
  every: true
  last: false

visualization:
  n_images_per_epoch: 3
  every: 1
