CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'

DATASET:
  DATASET: cityscapes
  ROOT: data/
  TEST_SET: 'list/cityscapes/val.lst'
  TRAIN_SET: 'list/cityscapes/train.lst'
  NUM_CLASSES: 2
MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar"
LOSS:
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  SHUFFLE: true
  BEGIN_EPOCH: 0
  RESUME: false
  IGNORE_LABEL: 255
TEST:
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
